-- PostgreSQL schema migration: 001_init
-- This file is executed once and recorded in schema_migrations.

CREATE TABLE IF NOT EXISTS identity (
			id varchar(32) PRIMARY KEY,
			name varchar(50) NOT NULL,
			sex varchar(10) NOT NULL,
			created_at timestamp NULL,
			last_used_at timestamp NULL
		);

CREATE INDEX IF NOT EXISTS idx_last_used_at ON identity (last_used_at DESC);

CREATE TABLE IF NOT EXISTS chat_favorites (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			identity_id varchar(32) NOT NULL,
			target_user_id varchar(64) NOT NULL,
			target_user_name varchar(64) NULL,
			create_time timestamp NOT NULL
		);

CREATE INDEX IF NOT EXISTS idx_identity_id ON chat_favorites (identity_id);

CREATE INDEX IF NOT EXISTS idx_target_user_id ON chat_favorites (target_user_id);

CREATE TABLE IF NOT EXISTS douyin_favorite_user (
			sec_user_id varchar(128) PRIMARY KEY,
			source_input text NULL,
			display_name varchar(128) NULL,
			avatar_url varchar(500) NULL,
			profile_url varchar(500) NULL,
			last_parsed_at timestamp NULL,
			last_parsed_count int NULL,
			last_parsed_raw text NULL,
			created_at timestamp NOT NULL,
			updated_at timestamp NOT NULL
		);

CREATE INDEX IF NOT EXISTS idx_dfu_updated_at ON douyin_favorite_user (updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_dfu_created_at ON douyin_favorite_user (created_at DESC);

CREATE TABLE IF NOT EXISTS douyin_favorite_aweme (
			aweme_id varchar(64) PRIMARY KEY,
			sec_user_id varchar(128) NULL,
			type varchar(16) NULL,
			description text NULL,
			cover_url varchar(500) NULL,
			raw_detail text NULL,
			created_at timestamp NOT NULL,
			updated_at timestamp NOT NULL
		);

CREATE INDEX IF NOT EXISTS idx_dfa_sec_user_id ON douyin_favorite_aweme (sec_user_id);

CREATE INDEX IF NOT EXISTS idx_dfa_updated_at ON douyin_favorite_aweme (updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_dfa_created_at ON douyin_favorite_aweme (created_at DESC);

CREATE TABLE IF NOT EXISTS douyin_favorite_user_aweme (
			sec_user_id varchar(128) NOT NULL,
			aweme_id varchar(64) NOT NULL,
			type varchar(16) NULL,
			description text NULL,
			cover_url varchar(500) NULL,
			downloads text NULL,
			sort_order int NOT NULL DEFAULT 2147483647,
			created_at timestamp NOT NULL,
			updated_at timestamp NOT NULL,
			PRIMARY KEY (sec_user_id, aweme_id)
		);

CREATE INDEX IF NOT EXISTS idx_dfua_user_sort_order ON douyin_favorite_user_aweme (sec_user_id, sort_order);

CREATE INDEX IF NOT EXISTS idx_dfua_user_created_at ON douyin_favorite_user_aweme (sec_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_dfua_user_updated_at ON douyin_favorite_user_aweme (sec_user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS douyin_favorite_user_tag (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name varchar(64) NOT NULL,
			sort_order int NOT NULL DEFAULT 0,
			created_at timestamp NOT NULL,
			updated_at timestamp NOT NULL,
			CONSTRAINT uk_dfut_name UNIQUE (name)
		);

CREATE INDEX IF NOT EXISTS idx_dfut_updated_at ON douyin_favorite_user_tag (updated_at DESC);

CREATE TABLE IF NOT EXISTS douyin_favorite_user_tag_map (
			sec_user_id varchar(128) NOT NULL,
			tag_id bigint NOT NULL,
			created_at timestamp NOT NULL,
			PRIMARY KEY (sec_user_id, tag_id)
		);

CREATE INDEX IF NOT EXISTS idx_dfutm_tag_id ON douyin_favorite_user_tag_map (tag_id);

CREATE TABLE IF NOT EXISTS douyin_favorite_aweme_tag (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name varchar(64) NOT NULL,
			sort_order int NOT NULL DEFAULT 0,
			created_at timestamp NOT NULL,
			updated_at timestamp NOT NULL,
			CONSTRAINT uk_dfat_name UNIQUE (name)
		);

CREATE INDEX IF NOT EXISTS idx_dfat_updated_at ON douyin_favorite_aweme_tag (updated_at DESC);

CREATE TABLE IF NOT EXISTS douyin_favorite_aweme_tag_map (
			aweme_id varchar(64) NOT NULL,
			tag_id bigint NOT NULL,
			created_at timestamp NOT NULL,
			PRIMARY KEY (aweme_id, tag_id)
		);

CREATE INDEX IF NOT EXISTS idx_dfatm_tag_id ON douyin_favorite_aweme_tag_map (tag_id);

CREATE TABLE IF NOT EXISTS media_file (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id varchar(32) NOT NULL,
			original_filename text NOT NULL,
			local_filename text NOT NULL,
			remote_filename text NOT NULL,
			remote_url varchar(500) NOT NULL,
			local_path varchar(500) NOT NULL,
			file_size bigint NOT NULL,
			file_type varchar(50) NOT NULL,
			file_extension varchar(10) NOT NULL,
			file_md5 varchar(32) NULL,
			upload_time timestamp NOT NULL,
			update_time timestamp NULL,
			created_at timestamp NOT NULL
		);

CREATE INDEX IF NOT EXISTS idx_mf_user_id ON media_file (user_id);

CREATE INDEX IF NOT EXISTS idx_mf_file_md5 ON media_file (file_md5);

CREATE INDEX IF NOT EXISTS idx_mf_update_time ON media_file (update_time DESC);

CREATE INDEX IF NOT EXISTS idx_mf_local_path ON media_file (local_path);

CREATE TABLE IF NOT EXISTS douyin_media_file (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id varchar(32) NOT NULL,
			sec_user_id varchar(128) NULL,
			detail_id varchar(64) NULL,
			original_filename text NOT NULL,
			local_filename text NOT NULL,
			remote_filename text NOT NULL,
			remote_url varchar(500) NOT NULL,
			local_path varchar(500) NOT NULL,
			file_size bigint NOT NULL,
			file_type varchar(50) NOT NULL,
			file_extension varchar(10) NOT NULL,
			file_md5 varchar(32) NULL,
			upload_time timestamp NOT NULL,
			update_time timestamp NULL,
			created_at timestamp NOT NULL
		);

CREATE INDEX IF NOT EXISTS idx_dmf_user_id ON douyin_media_file (user_id);

CREATE INDEX IF NOT EXISTS idx_dmf_sec_user_id ON douyin_media_file (sec_user_id);

CREATE INDEX IF NOT EXISTS idx_dmf_detail_id ON douyin_media_file (detail_id);

CREATE INDEX IF NOT EXISTS idx_dmf_sec_user_md5 ON douyin_media_file (sec_user_id, file_md5);

CREATE INDEX IF NOT EXISTS idx_dmf_user_md5 ON douyin_media_file (user_id, file_md5);

CREATE INDEX IF NOT EXISTS idx_dmf_file_md5 ON douyin_media_file (file_md5);

CREATE INDEX IF NOT EXISTS idx_dmf_update_time ON douyin_media_file (update_time DESC);

CREATE INDEX IF NOT EXISTS idx_dmf_local_path ON douyin_media_file (local_path);

CREATE TABLE IF NOT EXISTS media_send_log (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id varchar(32) NOT NULL,
			to_user_id varchar(32) NOT NULL,
			local_path varchar(500) NOT NULL,
			remote_url varchar(500) NOT NULL,
			send_time timestamp NOT NULL,
			created_at timestamp NOT NULL
		);

CREATE INDEX IF NOT EXISTS idx_msl_user_id ON media_send_log (user_id);

CREATE INDEX IF NOT EXISTS idx_msl_to_user_id ON media_send_log (to_user_id);

CREATE INDEX IF NOT EXISTS idx_msl_send_time ON media_send_log (send_time DESC);

CREATE TABLE IF NOT EXISTS media_upload_history (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id varchar(32) NOT NULL,
			to_user_id varchar(32) NULL,
			original_filename varchar(255) NOT NULL,
			local_filename varchar(255) NOT NULL,
			remote_filename varchar(255) NOT NULL,
			remote_url varchar(500) NOT NULL,
			local_path varchar(500) NOT NULL,
			file_size bigint NOT NULL,
			file_type varchar(50) NOT NULL,
			file_extension varchar(10) NOT NULL,
			upload_time timestamp NOT NULL,
			send_time timestamp NULL,
			file_md5 varchar(32) NULL,
			created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
		);

CREATE INDEX IF NOT EXISTS idx_muh_user_id ON media_upload_history (user_id);

CREATE INDEX IF NOT EXISTS idx_muh_to_user_id ON media_upload_history (to_user_id);

CREATE INDEX IF NOT EXISTS idx_muh_user_to_user ON media_upload_history (user_id, to_user_id, send_time DESC);

CREATE INDEX IF NOT EXISTS idx_muh_remote_url ON media_upload_history (remote_url);

CREATE INDEX IF NOT EXISTS idx_muh_upload_time ON media_upload_history (upload_time DESC);

CREATE INDEX IF NOT EXISTS idx_muh_file_md5 ON media_upload_history (file_md5);

CREATE TABLE IF NOT EXISTS image_hash (
			id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			file_path varchar(1000) NOT NULL,
			file_name varchar(255) NOT NULL,
			file_dir varchar(500) NULL,
			md5_hash varchar(32) NOT NULL,
			phash bigint NOT NULL,
			file_size bigint NULL,
			created_at timestamp NOT NULL
		);

CREATE INDEX IF NOT EXISTS idx_ih_md5_hash ON image_hash (md5_hash);

CREATE INDEX IF NOT EXISTS idx_ih_phash ON image_hash (phash);

CREATE TABLE IF NOT EXISTS system_config (
			config_key varchar(64) PRIMARY KEY,
			config_value text NOT NULL,
			created_at timestamp NOT NULL,
			updated_at timestamp NOT NULL
		);

CREATE TABLE IF NOT EXISTS video_extract_task (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			task_id varchar(64) NOT NULL,
			user_id varchar(32) NULL,
			source_type varchar(16) NOT NULL,
			source_ref varchar(500) NOT NULL,
			input_abs_path text NOT NULL,
			output_dir_local_path varchar(500) NOT NULL,
			output_format varchar(8) NOT NULL,
			jpg_quality int NULL,
			mode varchar(16) NOT NULL,
			keyframe_mode varchar(16) NULL,
			fps double precision NULL,
			scene_threshold double precision NULL,
			start_sec double precision NULL,
			end_sec double precision NULL,
			max_frames_total int NOT NULL,
			frames_extracted int NOT NULL,
			video_width int NOT NULL,
			video_height int NOT NULL,
			duration_sec double precision NULL,
			cursor_out_time_sec double precision NULL,
			status varchar(16) NOT NULL,
			stop_reason varchar(32) NULL,
			last_error text NULL,
			last_logs text NULL,
			created_at timestamp NOT NULL,
			updated_at timestamp NOT NULL,
			CONSTRAINT uk_vet_task_id UNIQUE (task_id)
		);

CREATE INDEX IF NOT EXISTS idx_vet_updated_at ON video_extract_task (updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_vet_user_id ON video_extract_task (user_id);

CREATE TABLE IF NOT EXISTS video_extract_frame (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			task_id varchar(64) NOT NULL,
			seq int NOT NULL,
			rel_path varchar(500) NOT NULL,
			time_sec double precision NULL,
			created_at timestamp NOT NULL,
			CONSTRAINT uk_vef_task_seq UNIQUE (task_id, seq)
		);

CREATE INDEX IF NOT EXISTS idx_vef_task_id ON video_extract_frame (task_id);

CREATE INDEX IF NOT EXISTS idx_vef_seq ON video_extract_frame (task_id, seq);
